gnn_learning_configs:
  # Dataset parameters
  input_dir: EMB_out
  output_dir: Datasets/GNN_output
  pt_signal_cut: 1.
  pt_background_cut: 1.
  split: [1000, 92, 91] # Number of [training, validation, testing] examples

  # Model parameters
  input_dim: 2
  hidden_dim: 128
  n_layers: 3
  node_encode_dim: 4
  edge_encode_dim: 4
  n_message_passing: 3
  edge_cut: 0.5
  seed: 1
  lr: 0.001
  factor: 0.7
  patience: 4
  margin: 0.1
  activation: ReLU
  layernorm: True
  weight: 1
  max_epochs: 2